services:
  app:
    image: mcr.microsoft.com/devcontainers/dotnet
    volumes:
      - .:/workspace
    depends_on:
      - sqlserver
      - dynamodb
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrong!Password"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  dynamodb:
    image: amazon/dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb"
    ports:
      - "8000:8000"